#RIC 을 사용할 경우
uicc0 = {
    imsi = "208950000007488";      # ← SQL과 동일하게
    key = "fec86ba6eb707ed08905757b1bb44b8f";
    opc = "C42449363BBAD02B66D16BC975D77CC1";
    dnn = "oai";
    nssai_sst = 1;
    nssai_sd  = "ffffff";         # ← 문자열 형식 유지
    
}

#UE를 gNB와 다른 호스트에서 실행할경우
#rfsimulator : {
#  serveraddr = "192.168.186.132";
#  serverport = 4043;
#}


position0 = {
    x = 0.0;
    y = 0.0;
    z = 6377900.0;
}

@include "channelmod_rfsimu_LEO_satellite.conf"
